### ISSUE TITLE
git push -u origin master

### ISSUE THREAD

**Issue by linuxserver2016** [antirez/redis-io#92]
when i try to run 
# git push -u origin master

Received the following errors in my centos gitlab installed machine.....
/usr/local/lib/ruby/2.1.0/uri/common.rb:176:in `split': bad URI(is not URI?): 192.168.5.13:8080/api/v3/internal/allowed (URI::InvalidURIError)

from /usr/local/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
    from /usr/local/lib/ruby/2.1.0/uri/common.rb:747:in`parse'
    from /home/git/gitlab-shell/lib/gitlab_net.rb:93:in `post'
    from /home/git/gitlab-shell/lib/gitlab_net.rb:27:in`allowed?'
    from /home/git/gitlab-shell/lib/gitlab_shell.rb:64:in `validate_access'
    from /home/git/gitlab-shell/lib/gitlab_shell.rb:25:in`exec'
    from /home/git/gitlab-shell/bin/gitlab-shell:16:in `<main>'
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by linuxserver2016** [comment]
i'm new to gitlab... please help to solve the issue,....
